[feat/user] Get All Api Update
medkickrpm/api pull request #38
Opened 2023-12-06 14:42 UTC by RedFC

2023-12-06 14:50 UTC, weje-air-business approved these changes

2023-12-06 20:46 UTC, Raajheer1 requested changes

2023-12-06 20:46 UTC, Raajheer1 commented on v1/user/auth.go
> +		fmt.Println(os.Getenv("SESSION_SECRET"))
Remove these print statements.

2023-12-07 17:40 UTC, weje-air-business approved these changes
1. Raaj change request is completed
2. Swagger issue resolved
3. Patient endpoints with filters reviewed on local

2023-12-07 17:41 UTC, merged